### ISSUE TITLE
OnMouseEnter on Custom Dialog Error

### ISSUE THREAD

**Issue by thatsjohnson** [raflop/ToastNotifications#43]
The same code works on 2.1.3, but on 2.2 it throws this exception when I move my mouse over the custom message to respond.

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at ToastNotifications.Core.NotificationDisplayPart.OnMouseEnter(MouseEventArgs e)
   at System.Windows.UIElement.OnMouseEnterThunk(Object sender, MouseEventArgs e)
   at System.Windows.Input.MouseEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.MouseOverProperty.FireNotifications(UIElement uie, ContentElement ce, UIElement3D uie3D, Boolean oldValue)
   at System.Windows.ReverseInheritProperty.FirePropThe thread 0x4044 has exited with code 0 (0x0).

**Comment by Darth-Alex** [comment]
Have the same Issue and found the Problem.
Look at that Line of Code: https://github.com/raflop/ToastNotifications/blob/master-v2/Src/ToastNotifications/Core/NotificationDisplayPart.cs#L36
Here is the first Possible Null Reference Exception. 
Not sure if its a Issue but you should override public override MessageOptions GetOptions() in your xaml.cs. In my case i set FreezeOnMouseEnter to false. 

Maybee GetOptionns() should be an abstract override.

**Comment by b-mi** [comment]
Yes, that null check is solution, I sent pull request with it (and with new CornerPosition - BottomCenter)

**Comment by thatsjohnson** [comment]
Thanks for verifying this. Look forward to the update.

**Comment by raflop** [comment]
Hi,
@b-mi thanks again for your great help, your changes are merged into master-v2 in version 2.21.
Nuget with the version is already published.

Best regards
