### ISSUE TITLE
Strange Error in Show Information Message

### ISSUE THREAD

**Issue by damonwildercarr** [raflop/ToastNotifications#64]
Very interesting - I get:

'M0,1.2857L3.5715,4.5 0,7.7143 1.4287,9 5,5.7857 8.5713,9 10,7.7143 6.4285,4.5 10,1.2857 8.5713,0 5,3.2143 1.4287,0 0,1.2857z' is not a valid value for property 'Visual'.

This is in a highly abstracted Prism-based WPF project. It works when all of the code is loaded explicitly, however when I dynamically pull this in I get the following.

Stack Trace:

   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at ToastNotifications.Messages.Information.InformationDisplayPart.InitializeComponent()
   at ToastNotifications.Messages.Information.InformationMessage.CreateDisplayPart()
   at ToastNotifications.Messages.Core.MessageBase`1.Configure()
   at ToastNotifications.Messages.Core.MessageBase`1.get_DisplayPart()
   at ToastNotifications.Display.NotificationsDisplaySupervisor.ShowNotification(INotification notification)
   at ToastNotifications.Display.NotificationsDisplaySupervisor.InternalDisplayNotification(INotification notification)
   at ToastNotifications.Display.NotificationsDisplaySupervisor.<>c__DisplayClass7_0.<DisplayNotification>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by damonwildercarr** [comment]
Disregard - this is on my side

**Comment by dustylau** [comment]
What was your issue? I am having a similar problem.
